name: Build and Deploy Vue
on:
  push:
    branches: [main]
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    name: Build Vue
    steps:
    - uses: actions/checkout@v2
    - id: Build-Vue
    - name: Build Vue
      run: |
            yarn install --frozen-lockfile; 
            yarn build;
            cd dist
            ln -s index.html 404.html
            git init
            git add -A
            git commit -m ''
            git push -f https://kelliedlynch:${{ secrets.GITHUB_TOKEN }}@github.com/kelliedlynch/sprinter.git main:gh-pages
      shell: bash
